import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import LatestBlogs from '../components/LatestBlogs'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>


			<Head>
				<title>Code Hunters</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>


			<main className={styles.main}>
				<h1 className={styles.title}>
					Code Hunters
				</h1>

				

				<img src="https://source.unsplash.com/300x300/?coder" alt="Code Hunters" className={styles.mainImg} />

				<LatestBlogs/>

			</main>
		</div>
	)
}
